# Skaffold deploys all files listed in this Directory (better than running k8s apply etc)
apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: torressam/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # HMR for any js file then applied to k8s pods (auth, client, etc...)
          - src: 'src/**/*{.ts, .js}'
            # Rebuild entire img if other non src/.ts file is changed
            dest: .
    - image: torressam/tickethub-client
      context: tickethub-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
