apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: torressam/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # HMR for any js file then applied to k8s pod
          - src: 'src/**/*.ts'
            # Rebuild entire img if other non src/.ys file is changed
            dest: .
