name: ticketing-tests

on:
  pull_request:
    paths:
      - 'ticketing/**' #Only run action if changes exist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing && npm install && npm run test:ci
